trigger:
- '*'

variables:
  buildConfiguration: 'Release'
  webRepository: 'web'
  tag: '$(Build.BuildId)' # Corrected capitalization

stages:
- stage: 'Build'
  displayName: 'Build and push'
  jobs:
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'ubuntu-20.04'
    steps:
    - task: Docker@2
      displayName: 'Build and push the image to container registry'
      inputs:
        command: buildAndPush
        buildContext: $(Build.Repository.LocalPath)
        repository: $(webRepository)
        dockerfile: '$(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/Dockerfile'
        containerRegistry: 'Container Registry Connection' # Make sure this connection exists
        tags: |
          $(tag)
- stage: 'Deploy'
  displayName: 'Deploy the container'
  dependsOn: Build
  jobs:
  - job: 'Deploy'
    displayName: 'Deploy job'
    pool:
      vmImage: 'ubuntu-20.04'
    variables:
    - group: Release # Ensure the Release variable group exists
    steps:
    - task: AzureWebAppContainer@1
      inputs:
        appName: $(WebAppName) # Check if this variable is defined in the Release group
        azureSubscription: 'Resource Manager - Tailspin - Space Game' # Check if this service connection exists
        imageName: $(RegistryName)/$(webRepository):$(Build.BuildId) # Corrected capitalization here as well